layout_spectrum: 0.4516825322061777
typography_spectrum: 0.8616913163568825
color:
  saturation: 0.8733926995191723
  brandStrength: 0.19801974529400468
  rhythmicContrast: 0.2024230659008026
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  lightness: 0.4169676264282316
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
name: Out of the Office
